-- =============================================================================
-- SylviaNG.Community — Consolidated PostgreSQL Database Script
-- =============================================================================
-- Generated with: dotnet ef migrations script --no-build
-- (run from SylviaNG.Community-master/SylviaNG.Community-master/SylviaNG.Community)
--
-- This single script combines all EF Core migrations, in order, into one
-- deployable unit for PostgreSQL. Migration source files remain the source of
-- truth for schema changes going forward (`dotnet ef migrations add ...`);
-- this file is a convenience export for anyone who needs to stand up the
-- database in one step without the .NET/EF CLI tooling.
--
-- Usage (fresh, empty PostgreSQL database):
--   psql -h <host> -U <user> -d <database> -f database_script.sql
--
-- The script populates "__EFMigrationsHistory" as it applies each migration,
-- so a database created from this file remains compatible with
-- `dotnet ef database update` for any future migrations.
--
-- Regenerate after adding new migrations with:
--   dotnet ef migrations script --no-build -o database_script.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Announcements" (
    "AnnouncementId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SiteId" bigint NOT NULL,
    "DepartmentId" bigint,
    "Title" character varying(200) NOT NULL,
    "Body" text,
    "AnnouncementType" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "PublishDate" timestamp with time zone,
    "ExpiryDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_Announcements" PRIMARY KEY ("AnnouncementId")
);

CREATE TABLE "Employees" (
    "EmployeeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeName" character varying(200),
    "EmployeeCode" character varying(50),
    "DepartmentId" bigint,
    "DesignatioId" bigint,
    "SiteId" bigint,
    "RFId" bigint,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("EmployeeId")
);

INSERT INTO "Announcements" ("AnnouncementId", "AnnouncementType", "Body", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "DepartmentId", "ExpiryDate", "IsActive", "PublishDate", "Remarks", "SiteId", "Status", "TenantId", "Title", "UpdatedAt", "UpdatedBy")
VALUES (1, 'General', 'Stay connected with company news, events, and announcements.', TIMESTAMPTZ '2025-01-01T00:00:00Z', 1, NULL, NULL, NULL, NULL, TRUE, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, 1, 'Published', 'default_tenant', 'Welcome to SylviaNG Community', NULL, NULL);
INSERT INTO "Announcements" ("AnnouncementId", "AnnouncementType", "Body", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "DepartmentId", "ExpiryDate", "IsActive", "PublishDate", "Remarks", "SiteId", "Status", "TenantId", "Title", "UpdatedAt", "UpdatedBy")
VALUES (2, 'Event', 'Join us for our annual company picnic this weekend at the lakeside.', TIMESTAMPTZ '2025-05-01T00:00:00Z', 1, NULL, NULL, NULL, TIMESTAMPTZ '2025-07-01T00:00:00Z', TRUE, TIMESTAMPTZ '2025-06-15T00:00:00Z', NULL, 1, 'Scheduled', 'default_tenant', 'Annual Company Picnic', NULL, NULL);

CREATE INDEX "IX_Announcements_SiteId" ON "Announcements" ("SiteId");

CREATE UNIQUE INDEX "IX_Announcements_SiteId_Title" ON "Announcements" ("SiteId", "Title");

CREATE INDEX "IX_Announcements_Status" ON "Announcements" ("Status");

CREATE INDEX "IX_Employees_EmployeeCode" ON "Employees" ("EmployeeCode");

SELECT setval(
    pg_get_serial_sequence('"Announcements"', 'AnnouncementId'),
    GREATEST(
        (SELECT MAX("AnnouncementId") FROM "Announcements") + 1,
        nextval(pg_get_serial_sequence('"Announcements"', 'AnnouncementId'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260623064125_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" ADD "Achievements" text;

ALTER TABLE "Employees" ADD "Bio" text;

ALTER TABLE "Employees" ADD "CommunityContributions" text;

ALTER TABLE "Employees" ADD "Division" character varying(200);

ALTER TABLE "Employees" ADD "Email" character varying(200);

ALTER TABLE "Employees" ADD "EmailVisibility" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Employees" ADD "Extension" character varying(20);

ALTER TABLE "Employees" ADD "ExtensionVisibility" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Employees" ADD "GradeId" bigint;

ALTER TABLE "Employees" ADD "Interests" text;

ALTER TABLE "Employees" ADD "IsActive" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Employees" ADD "Phone" character varying(50);

ALTER TABLE "Employees" ADD "PhoneVisibility" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Employees" ADD "PhotoUrl" character varying(500);

ALTER TABLE "Employees" ADD "Skills" text;

INSERT INTO "Employees" ("EmployeeId", "Achievements", "Bio", "CommunityContributions", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "DepartmentId", "DesignatioId", "Division", "Email", "EmailVisibility", "EmployeeCode", "EmployeeName", "Extension", "ExtensionVisibility", "GradeId", "Interests", "IsActive", "Phone", "PhoneVisibility", "PhotoUrl", "RFId", "Remarks", "SiteId", "Skills", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (1, NULL, 'Frontend engineer who enjoys mentoring new hires.', NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 1, 1, 'Engineering', 'ayesha.rahman@sylviang.example', 'Private', 'EMP00001', 'Ayesha Rahman', '1001', 'Private', NULL, 'Photography, Chess', TRUE, '+880-1710-000001', 'Private', NULL, NULL, NULL, 1, 'Angular, TypeScript, PrimeNG', 1, 'default_tenant', NULL, NULL);
INSERT INTO "Employees" ("EmployeeId", "Achievements", "Bio", "CommunityContributions", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "DepartmentId", "DesignatioId", "Division", "Email", "EmailVisibility", "EmployeeCode", "EmployeeName", "Extension", "ExtensionVisibility", "GradeId", "Interests", "IsActive", "Phone", "PhoneVisibility", "PhotoUrl", "RFId", "Remarks", "SiteId", "Skills", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (2, NULL, 'Engineering team lead focused on delivery quality.', NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 1, 2, 'Engineering', 'tanvir.hasan@sylviang.example', 'Public', 'EMP00002', 'Tanvir Hasan', '1002', 'Private', NULL, 'Cricket, Reading', TRUE, '+880-1710-000002', 'Public', NULL, NULL, NULL, 1, 'Leadership, .NET, SQL', 1, 'default_tenant', NULL, NULL);
INSERT INTO "Employees" ("EmployeeId", "Achievements", "Bio", "CommunityContributions", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "DepartmentId", "DesignatioId", "Division", "Email", "EmailVisibility", "EmployeeCode", "EmployeeName", "Extension", "ExtensionVisibility", "GradeId", "Interests", "IsActive", "Phone", "PhoneVisibility", "PhotoUrl", "RFId", "Remarks", "SiteId", "Skills", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (3, NULL, 'HR Business Partner supporting the engineering org.', NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, 2, 3, 'People & Culture', 'farhana.akter@sylviang.example', 'Public', 'EMP00003', 'Farhana Akter', '1003', 'Private', NULL, 'Yoga, Travel', TRUE, '+880-1710-000003', 'Private', NULL, NULL, NULL, 1, 'Recruiting, Employee Relations', 1, 'default_tenant', NULL, NULL);

CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");

CREATE INDEX "IX_Employees_IsActive" ON "Employees" ("IsActive");

CREATE INDEX "IX_Employees_SiteId" ON "Employees" ("SiteId");

SELECT setval(
    pg_get_serial_sequence('"Employees"', 'EmployeeId'),
    GREATEST(
        (SELECT MAX("EmployeeId") FROM "Employees") + 1,
        nextval(pg_get_serial_sequence('"Employees"', 'EmployeeId'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260713142010_AddEmployeeProfileFields', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "Teams" (
    "TeamId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "SupervisorId" bigint,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Teams" PRIMARY KEY ("TeamId")
);

CREATE TABLE "TeamMembers" (
    "TeamMemberId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TeamId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "JoinedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TeamMembers" PRIMARY KEY ("TeamMemberId"),
    CONSTRAINT "FK_TeamMembers_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("TeamId") ON DELETE CASCADE
);

CREATE INDEX "IX_TeamMembers_EmployeeId" ON "TeamMembers" ("EmployeeId");

CREATE UNIQUE INDEX "IX_TeamMembers_TeamId_EmployeeId" ON "TeamMembers" ("TeamId", "EmployeeId");

CREATE INDEX "IX_Teams_IsActive" ON "Teams" ("IsActive");

CREATE INDEX "IX_Teams_SupervisorId" ON "Teams" ("SupervisorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260726121114_AddTeamModule', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "ActivityLogs" (
    "ActivityId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "Module" character varying(100) NOT NULL,
    "Action" character varying(100) NOT NULL,
    "EntityType" character varying(100),
    "EntityId" bigint,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("ActivityId")
);

CREATE TABLE "AuditLogs" (
    "AuditId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TableName" character varying(200) NOT NULL,
    "RecordId" bigint NOT NULL,
    "Action" character varying(50) NOT NULL,
    "OldValue" text,
    "NewValue" text,
    "PerformedBy" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("AuditId")
);

CREATE TABLE "Badges" (
    "BadgeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Icon" character varying(300),
    "Description" text,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Badges" PRIMARY KEY ("BadgeId")
);

CREATE TABLE "DashboardPreferences" (
    "PreferenceId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "WidgetName" character varying(100) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "IsVisible" boolean NOT NULL,
    "LastModified" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_DashboardPreferences" PRIMARY KEY ("PreferenceId")
);

CREATE TABLE "Elections" (
    "ElectionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "ElectionType" character varying(50) NOT NULL,
    "CandidateType" character varying(50) NOT NULL,
    "AudienceScope" character varying(50) NOT NULL,
    "IsAnonymous" boolean NOT NULL,
    "AllowMultipleChoice" boolean NOT NULL,
    "MinSelection" integer NOT NULL,
    "MaxSelection" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "Status" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_Elections" PRIMARY KEY ("ElectionId")
);

CREATE TABLE "FileStorages" (
    "FileId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Module" character varying(100) NOT NULL,
    "EntityId" bigint,
    "FileName" character varying(255) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "FileExtension" character varying(20),
    "MimeType" character varying(100),
    "FileSize" bigint NOT NULL,
    "StoragePath" character varying(500) NOT NULL,
    "UploadedBy" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_FileStorages" PRIMARY KEY ("FileId")
);

CREATE TABLE "Interests" (
    "InterestId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Interests" PRIMARY KEY ("InterestId")
);

CREATE TABLE "Listings" (
    "ListingId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SellerId" bigint NOT NULL,
    "ListingType" character varying(50) NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Category" character varying(100) NOT NULL,
    "Condition" character varying(50),
    "Price" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "Location" character varying(200),
    "Status" character varying(50) NOT NULL,
    "ApprovalStatus" character varying(50) NOT NULL,
    "ApprovedBy" bigint,
    "ApprovedAt" timestamp with time zone,
    "RejectionReason" text,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_Listings" PRIMARY KEY ("ListingId")
);

CREATE TABLE "Mentions" (
    "MentionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MentionedEmployeeId" bigint NOT NULL,
    "MentionedBy" bigint NOT NULL,
    "EntityType" character varying(50) NOT NULL,
    "EntityId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Mentions" PRIMARY KEY ("MentionId")
);

CREATE TABLE "NotificationPreferences" (
    "PreferenceId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "Category" character varying(100) NOT NULL,
    "InAppEnabled" boolean NOT NULL,
    "EmailEnabled" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("PreferenceId")
);

CREATE TABLE "Notifications" (
    "NotificationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" text,
    "Category" character varying(100),
    "RelatedEntityType" character varying(100),
    "RelatedEntityId" bigint,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId")
);

CREATE TABLE "Posts" (
    "PostId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Visibility" character varying(50) NOT NULL,
    "Content" text,
    "IsAnnouncement" boolean NOT NULL,
    "IsPoll" boolean NOT NULL,
    "IsLocked" boolean NOT NULL,
    "IsHidden" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("PostId")
);

CREATE TABLE "Recognitions" (
    "RecognitionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" bigint NOT NULL,
    "RecipientId" bigint NOT NULL,
    "RecognitionType" character varying(100) NOT NULL,
    "CoreValue" character varying(100),
    "AwardTitle" character varying(200),
    "Message" text,
    "IsPublic" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Recognitions" PRIMARY KEY ("RecognitionId")
);

CREATE TABLE "RecurringTasks" (
    "RecurringTaskId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Frequency" character varying(50) NOT NULL,
    "IntervalValue" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_RecurringTasks" PRIMARY KEY ("RecurringTaskId")
);

CREATE TABLE "Skills" (
    "SkillId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("SkillId")
);

CREATE TABLE "Surveys" (
    "SurveyId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "SurveyType" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "IsAnonymous" boolean NOT NULL,
    "IsMandatory" boolean NOT NULL,
    "PublishedAt" timestamp with time zone,
    "ClosedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_Surveys" PRIMARY KEY ("SurveyId")
);

CREATE TABLE "TaskTags" (
    "TagId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TaskTags" PRIMARY KEY ("TagId")
);

CREATE TABLE "EmployeeBadges" (
    "EmployeeBadgeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "BadgeId" bigint NOT NULL,
    "AwardedDate" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EmployeeBadges" PRIMARY KEY ("EmployeeBadgeId"),
    CONSTRAINT "FK_EmployeeBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("BadgeId") ON DELETE CASCADE
);

CREATE TABLE "ElectionAudienceTargets" (
    "ElectionAudienceTargetId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ElectionId" bigint NOT NULL,
    "TargetId" character varying(200) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ElectionAudienceTargets" PRIMARY KEY ("ElectionAudienceTargetId"),
    CONSTRAINT "FK_ElectionAudienceTargets_Elections_ElectionId" FOREIGN KEY ("ElectionId") REFERENCES "Elections" ("ElectionId") ON DELETE CASCADE
);

CREATE TABLE "ElectionCandidates" (
    "ElectionCandidateId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ElectionId" bigint NOT NULL,
    "EmployeeId" bigint,
    "TeamId" bigint,
    "CandidateType" character varying(50) NOT NULL,
    "Manifesto" text,
    "IsApproved" boolean NOT NULL,
    "NominatedAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ElectionCandidates" PRIMARY KEY ("ElectionCandidateId"),
    CONSTRAINT "FK_ElectionCandidates_Elections_ElectionId" FOREIGN KEY ("ElectionId") REFERENCES "Elections" ("ElectionId") ON DELETE CASCADE,
    CONSTRAINT "FK_ElectionCandidates_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("TeamId") ON DELETE RESTRICT
);

CREATE TABLE "EmployeeInterests" (
    "EmployeeInterestId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "InterestId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EmployeeInterests" PRIMARY KEY ("EmployeeInterestId"),
    CONSTRAINT "FK_EmployeeInterests_Interests_InterestId" FOREIGN KEY ("InterestId") REFERENCES "Interests" ("InterestId") ON DELETE CASCADE
);

CREATE TABLE "Conversations" (
    "ConversationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" bigint NOT NULL,
    "Status" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("ConversationId"),
    CONSTRAINT "FK_Conversations_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE CASCADE
);

CREATE TABLE "Favorites" (
    "FavoriteId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "ListingId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("FavoriteId"),
    CONSTRAINT "FK_Favorites_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE CASCADE
);

CREATE TABLE "ListingImages" (
    "ImageId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" bigint NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ListingImages" PRIMARY KEY ("ImageId"),
    CONSTRAINT "FK_ListingImages_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE CASCADE
);

CREATE TABLE "MarketplaceReports" (
    "ReportId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" bigint NOT NULL,
    "ReportedBy" bigint NOT NULL,
    "Reason" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ReviewedBy" bigint,
    "ReviewedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_MarketplaceReports" PRIMARY KEY ("ReportId"),
    CONSTRAINT "FK_MarketplaceReports_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE CASCADE
);

CREATE TABLE "ContentReports" (
    "ReportId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReportedBy" bigint NOT NULL,
    "PostId" bigint NOT NULL,
    "Reason" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ReviewedBy" bigint,
    "ReviewedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_ContentReports" PRIMARY KEY ("ReportId"),
    CONSTRAINT "FK_ContentReports_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE RESTRICT
);

CREATE TABLE "Polls" (
    "PollId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PostId" bigint NOT NULL,
    "AllowVoteChange" boolean NOT NULL,
    "ExpirationDate" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Polls" PRIMARY KEY ("PollId"),
    CONSTRAINT "FK_Polls_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE CASCADE
);

CREATE TABLE "PostAttachments" (
    "AttachmentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PostId" bigint NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FileType" character varying(100),
    "FilePath" character varying(1000) NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PostAttachments" PRIMARY KEY ("AttachmentId"),
    CONSTRAINT "FK_PostAttachments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE CASCADE
);

CREATE TABLE "PostComments" (
    "CommentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PostId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ParentCommentId" bigint,
    "Content" text NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PostComments" PRIMARY KEY ("CommentId"),
    CONSTRAINT "FK_PostComments_PostComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "PostComments" ("CommentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_PostComments_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE CASCADE
);

CREATE TABLE "PostReactions" (
    "ReactionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PostId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ReactionType" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PostReactions" PRIMARY KEY ("ReactionId"),
    CONSTRAINT "FK_PostReactions_Posts_PostId" FOREIGN KEY ("PostId") REFERENCES "Posts" ("PostId") ON DELETE CASCADE
);

CREATE TABLE "RecognitionComments" (
    "CommentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RecognitionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ParentCommentId" bigint,
    "Comment" text NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_RecognitionComments" PRIMARY KEY ("CommentId"),
    CONSTRAINT "FK_RecognitionComments_RecognitionComments_ParentCommentId" FOREIGN KEY ("ParentCommentId") REFERENCES "RecognitionComments" ("CommentId") ON DELETE RESTRICT,
    CONSTRAINT "FK_RecognitionComments_Recognitions_RecognitionId" FOREIGN KEY ("RecognitionId") REFERENCES "Recognitions" ("RecognitionId") ON DELETE CASCADE
);

CREATE TABLE "RecognitionReactions" (
    "ReactionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RecognitionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ReactionType" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_RecognitionReactions" PRIMARY KEY ("ReactionId"),
    CONSTRAINT "FK_RecognitionReactions_Recognitions_RecognitionId" FOREIGN KEY ("RecognitionId") REFERENCES "Recognitions" ("RecognitionId") ON DELETE CASCADE
);

CREATE TABLE "Tasks" (
    "TaskId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TeamId" bigint NOT NULL,
    "AssignedBy" bigint NOT NULL,
    "AssignedTo" bigint NOT NULL,
    "RecurringTaskId" bigint,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Priority" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "DueDate" timestamp with time zone,
    "ReminderDays" integer,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status1" integer NOT NULL,
    CONSTRAINT "PK_Tasks" PRIMARY KEY ("TaskId"),
    CONSTRAINT "FK_Tasks_RecurringTasks_RecurringTaskId" FOREIGN KEY ("RecurringTaskId") REFERENCES "RecurringTasks" ("RecurringTaskId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tasks_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("TeamId") ON DELETE CASCADE
);

CREATE TABLE "EmployeeSkills" (
    "EmployeeSkillId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "SkillId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EmployeeSkills" PRIMARY KEY ("EmployeeSkillId"),
    CONSTRAINT "FK_EmployeeSkills_Skills_SkillId" FOREIGN KEY ("SkillId") REFERENCES "Skills" ("SkillId") ON DELETE CASCADE
);

CREATE TABLE "SurveyAudiences" (
    "AudienceId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SurveyId" bigint NOT NULL,
    "AudienceType" character varying(50) NOT NULL,
    "DepartmentId" bigint,
    "BranchId" bigint,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SurveyAudiences" PRIMARY KEY ("AudienceId"),
    CONSTRAINT "FK_SurveyAudiences_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("SurveyId") ON DELETE CASCADE
);

CREATE TABLE "SurveyQuestions" (
    "QuestionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SurveyId" bigint NOT NULL,
    "QuestionText" text NOT NULL,
    "QuestionType" character varying(50) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "IsRequired" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SurveyQuestions" PRIMARY KEY ("QuestionId"),
    CONSTRAINT "FK_SurveyQuestions_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("SurveyId") ON DELETE CASCADE
);

CREATE TABLE "SurveyResponses" (
    "ResponseId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SurveyId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "CompletionStatus" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SurveyResponses" PRIMARY KEY ("ResponseId"),
    CONSTRAINT "FK_SurveyResponses_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId") ON DELETE RESTRICT,
    CONSTRAINT "FK_SurveyResponses_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES "Surveys" ("SurveyId") ON DELETE CASCADE
);

CREATE TABLE "ElectionVotes" (
    "ElectionVoteId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ElectionId" bigint NOT NULL,
    "CandidateId" bigint NOT NULL,
    "VoterId" bigint NOT NULL,
    "VotedAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ElectionVotes" PRIMARY KEY ("ElectionVoteId"),
    CONSTRAINT "FK_ElectionVotes_ElectionCandidates_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "ElectionCandidates" ("ElectionCandidateId") ON DELETE RESTRICT,
    CONSTRAINT "FK_ElectionVotes_Elections_ElectionId" FOREIGN KEY ("ElectionId") REFERENCES "Elections" ("ElectionId") ON DELETE CASCADE
);

CREATE TABLE "ConversationParticipants" (
    "ParticipantId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ConversationParticipants" PRIMARY KEY ("ParticipantId"),
    CONSTRAINT "FK_ConversationParticipants_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("ConversationId") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "MessageId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" bigint NOT NULL,
    "SenderId" bigint NOT NULL,
    "MessageText" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("ConversationId") ON DELETE CASCADE
);

CREATE TABLE "PollOptions" (
    "PollOptionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PollId" bigint NOT NULL,
    "OptionText" character varying(500) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PollOptions" PRIMARY KEY ("PollOptionId"),
    CONSTRAINT "FK_PollOptions_Polls_PollId" FOREIGN KEY ("PollId") REFERENCES "Polls" ("PollId") ON DELETE CASCADE
);

CREATE TABLE "CommentReactions" (
    "ReactionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CommentId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ReactionType" character varying(50) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_CommentReactions" PRIMARY KEY ("ReactionId"),
    CONSTRAINT "FK_CommentReactions_PostComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "PostComments" ("CommentId") ON DELETE CASCADE
);

CREATE TABLE "TaskAttachments" (
    "AttachmentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FileType" character varying(100),
    "FilePath" character varying(1000) NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedBy" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TaskAttachments" PRIMARY KEY ("AttachmentId"),
    CONSTRAINT "FK_TaskAttachments_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("TaskId") ON DELETE CASCADE
);

CREATE TABLE "TaskComments" (
    "CommentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "Comment" text NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TaskComments" PRIMARY KEY ("CommentId"),
    CONSTRAINT "FK_TaskComments_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("TaskId") ON DELETE CASCADE
);

CREATE TABLE "TaskHistories" (
    "HistoryId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "Action" character varying(100) NOT NULL,
    "OldValue" text,
    "NewValue" text,
    "ChangedBy" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TaskHistories" PRIMARY KEY ("HistoryId"),
    CONSTRAINT "FK_TaskHistories_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("TaskId") ON DELETE CASCADE
);

CREATE TABLE "TaskTagMappings" (
    "MappingId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "TagId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_TaskTagMappings" PRIMARY KEY ("MappingId"),
    CONSTRAINT "FK_TaskTagMappings_TaskTags_TagId" FOREIGN KEY ("TagId") REFERENCES "TaskTags" ("TagId") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskTagMappings_Tasks_TaskId" FOREIGN KEY ("TaskId") REFERENCES "Tasks" ("TaskId") ON DELETE CASCADE
);

CREATE TABLE "SurveyOptions" (
    "OptionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" bigint NOT NULL,
    "OptionText" character varying(500) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SurveyOptions" PRIMARY KEY ("OptionId"),
    CONSTRAINT "FK_SurveyOptions_SurveyQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "SurveyQuestions" ("QuestionId") ON DELETE CASCADE
);

CREATE TABLE "PollVotes" (
    "VoteId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PollOptionId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "VotedAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_PollVotes" PRIMARY KEY ("VoteId"),
    CONSTRAINT "FK_PollVotes_PollOptions_PollOptionId" FOREIGN KEY ("PollOptionId") REFERENCES "PollOptions" ("PollOptionId") ON DELETE CASCADE
);

CREATE TABLE "SurveyAnswers" (
    "AnswerId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ResponseId" bigint NOT NULL,
    "QuestionId" bigint NOT NULL,
    "OptionId" bigint,
    "AnswerText" text,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_SurveyAnswers" PRIMARY KEY ("AnswerId"),
    CONSTRAINT "FK_SurveyAnswers_SurveyOptions_OptionId" FOREIGN KEY ("OptionId") REFERENCES "SurveyOptions" ("OptionId") ON DELETE RESTRICT,
    CONSTRAINT "FK_SurveyAnswers_SurveyQuestions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "SurveyQuestions" ("QuestionId") ON DELETE RESTRICT,
    CONSTRAINT "FK_SurveyAnswers_SurveyResponses_ResponseId" FOREIGN KEY ("ResponseId") REFERENCES "SurveyResponses" ("ResponseId") ON DELETE CASCADE
);

CREATE INDEX "IX_ActivityLogs_EmployeeId" ON "ActivityLogs" ("EmployeeId");

CREATE INDEX "IX_ActivityLogs_EntityType" ON "ActivityLogs" ("EntityType");

CREATE INDEX "IX_ActivityLogs_Module" ON "ActivityLogs" ("Module");

CREATE INDEX "IX_AuditLogs_PerformedBy" ON "AuditLogs" ("PerformedBy");

CREATE INDEX "IX_AuditLogs_TableName_RecordId" ON "AuditLogs" ("TableName", "RecordId");

CREATE UNIQUE INDEX "IX_Badges_Name" ON "Badges" ("Name");

CREATE UNIQUE INDEX "IX_CommentReactions_CommentId_EmployeeId" ON "CommentReactions" ("CommentId", "EmployeeId");

CREATE INDEX "IX_CommentReactions_EmployeeId" ON "CommentReactions" ("EmployeeId");

CREATE INDEX "IX_ContentReports_PostId" ON "ContentReports" ("PostId");

CREATE INDEX "IX_ContentReports_ReportedBy" ON "ContentReports" ("ReportedBy");

CREATE INDEX "IX_ContentReports_Status" ON "ContentReports" ("Status");

CREATE UNIQUE INDEX "IX_ConversationParticipants_ConversationId_EmployeeId" ON "ConversationParticipants" ("ConversationId", "EmployeeId");

CREATE INDEX "IX_ConversationParticipants_EmployeeId" ON "ConversationParticipants" ("EmployeeId");

CREATE INDEX "IX_Conversations_ListingId" ON "Conversations" ("ListingId");

CREATE UNIQUE INDEX "IX_DashboardPreferences_EmployeeId_WidgetName" ON "DashboardPreferences" ("EmployeeId", "WidgetName");

CREATE INDEX "IX_ElectionAudienceTargets_ElectionId" ON "ElectionAudienceTargets" ("ElectionId");

CREATE INDEX "IX_ElectionCandidates_ElectionId" ON "ElectionCandidates" ("ElectionId");

CREATE INDEX "IX_ElectionCandidates_EmployeeId" ON "ElectionCandidates" ("EmployeeId");

CREATE INDEX "IX_ElectionCandidates_TeamId" ON "ElectionCandidates" ("TeamId");

CREATE INDEX "IX_Elections_CreatedBy" ON "Elections" ("CreatedBy");

CREATE INDEX "IX_Elections_StartDate" ON "Elections" ("StartDate");

CREATE INDEX "IX_Elections_Status" ON "Elections" ("Status");

CREATE INDEX "IX_ElectionVotes_CandidateId" ON "ElectionVotes" ("CandidateId");

CREATE INDEX "IX_ElectionVotes_ElectionId" ON "ElectionVotes" ("ElectionId");

CREATE INDEX "IX_ElectionVotes_VoterId" ON "ElectionVotes" ("VoterId");

CREATE INDEX "IX_EmployeeBadges_BadgeId" ON "EmployeeBadges" ("BadgeId");

CREATE INDEX "IX_EmployeeBadges_EmployeeId" ON "EmployeeBadges" ("EmployeeId");

CREATE INDEX "IX_EmployeeBadges_EmployeeId_BadgeId" ON "EmployeeBadges" ("EmployeeId", "BadgeId");

CREATE INDEX "IX_EmployeeInterests_EmployeeId" ON "EmployeeInterests" ("EmployeeId");

CREATE UNIQUE INDEX "IX_EmployeeInterests_EmployeeId_InterestId" ON "EmployeeInterests" ("EmployeeId", "InterestId");

CREATE INDEX "IX_EmployeeInterests_InterestId" ON "EmployeeInterests" ("InterestId");

CREATE INDEX "IX_EmployeeSkills_EmployeeId" ON "EmployeeSkills" ("EmployeeId");

CREATE UNIQUE INDEX "IX_EmployeeSkills_EmployeeId_SkillId" ON "EmployeeSkills" ("EmployeeId", "SkillId");

CREATE INDEX "IX_EmployeeSkills_SkillId" ON "EmployeeSkills" ("SkillId");

CREATE UNIQUE INDEX "IX_Favorites_EmployeeId_ListingId" ON "Favorites" ("EmployeeId", "ListingId");

CREATE INDEX "IX_Favorites_ListingId" ON "Favorites" ("ListingId");

CREATE INDEX "IX_FileStorages_EntityId" ON "FileStorages" ("EntityId");

CREATE INDEX "IX_FileStorages_Module" ON "FileStorages" ("Module");

CREATE INDEX "IX_FileStorages_UploadedBy" ON "FileStorages" ("UploadedBy");

CREATE UNIQUE INDEX "IX_Interests_Name" ON "Interests" ("Name");

CREATE INDEX "IX_ListingImages_ListingId" ON "ListingImages" ("ListingId");

CREATE INDEX "IX_Listings_ApprovalStatus" ON "Listings" ("ApprovalStatus");

CREATE INDEX "IX_Listings_Category" ON "Listings" ("Category");

CREATE INDEX "IX_Listings_SellerId" ON "Listings" ("SellerId");

CREATE INDEX "IX_Listings_Status" ON "Listings" ("Status");

CREATE INDEX "IX_MarketplaceReports_ListingId" ON "MarketplaceReports" ("ListingId");

CREATE INDEX "IX_MarketplaceReports_ReportedBy" ON "MarketplaceReports" ("ReportedBy");

CREATE INDEX "IX_MarketplaceReports_Status" ON "MarketplaceReports" ("Status");

CREATE INDEX "IX_Mentions_EntityType_EntityId" ON "Mentions" ("EntityType", "EntityId");

CREATE INDEX "IX_Mentions_MentionedBy" ON "Mentions" ("MentionedBy");

CREATE INDEX "IX_Mentions_MentionedEmployeeId" ON "Mentions" ("MentionedEmployeeId");

CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE UNIQUE INDEX "IX_NotificationPreferences_EmployeeId_Category" ON "NotificationPreferences" ("EmployeeId", "Category");

CREATE INDEX "IX_Notifications_Category" ON "Notifications" ("Category");

CREATE INDEX "IX_Notifications_EmployeeId" ON "Notifications" ("EmployeeId");

CREATE INDEX "IX_Notifications_IsRead" ON "Notifications" ("IsRead");

CREATE INDEX "IX_PollOptions_PollId" ON "PollOptions" ("PollId");

CREATE UNIQUE INDEX "IX_Polls_PostId" ON "Polls" ("PostId");

CREATE INDEX "IX_PollVotes_EmployeeId" ON "PollVotes" ("EmployeeId");

CREATE INDEX "IX_PollVotes_PollOptionId" ON "PollVotes" ("PollOptionId");

CREATE INDEX "IX_PostAttachments_PostId" ON "PostAttachments" ("PostId");

CREATE INDEX "IX_PostComments_EmployeeId" ON "PostComments" ("EmployeeId");

CREATE INDEX "IX_PostComments_ParentCommentId" ON "PostComments" ("ParentCommentId");

CREATE INDEX "IX_PostComments_PostId" ON "PostComments" ("PostId");

CREATE INDEX "IX_PostReactions_EmployeeId" ON "PostReactions" ("EmployeeId");

CREATE UNIQUE INDEX "IX_PostReactions_PostId_EmployeeId" ON "PostReactions" ("PostId", "EmployeeId");

CREATE INDEX "IX_Posts_EmployeeId" ON "Posts" ("EmployeeId");

CREATE INDEX "IX_Posts_IsHidden" ON "Posts" ("IsHidden");

CREATE INDEX "IX_Posts_Type" ON "Posts" ("Type");

CREATE INDEX "IX_Posts_Visibility" ON "Posts" ("Visibility");

CREATE INDEX "IX_RecognitionComments_ParentCommentId" ON "RecognitionComments" ("ParentCommentId");

CREATE INDEX "IX_RecognitionComments_RecognitionId" ON "RecognitionComments" ("RecognitionId");

CREATE UNIQUE INDEX "IX_RecognitionReactions_RecognitionId_EmployeeId" ON "RecognitionReactions" ("RecognitionId", "EmployeeId");

CREATE INDEX "IX_Recognitions_RecipientId" ON "Recognitions" ("RecipientId");

CREATE INDEX "IX_Recognitions_SenderId" ON "Recognitions" ("SenderId");

CREATE INDEX "IX_RecurringTasks_IsActive" ON "RecurringTasks" ("IsActive");

CREATE UNIQUE INDEX "IX_Skills_Name" ON "Skills" ("Name");

CREATE INDEX "IX_SurveyAnswers_OptionId" ON "SurveyAnswers" ("OptionId");

CREATE INDEX "IX_SurveyAnswers_QuestionId" ON "SurveyAnswers" ("QuestionId");

CREATE INDEX "IX_SurveyAnswers_ResponseId" ON "SurveyAnswers" ("ResponseId");

CREATE INDEX "IX_SurveyAudiences_BranchId" ON "SurveyAudiences" ("BranchId");

CREATE INDEX "IX_SurveyAudiences_DepartmentId" ON "SurveyAudiences" ("DepartmentId");

CREATE INDEX "IX_SurveyAudiences_SurveyId" ON "SurveyAudiences" ("SurveyId");

CREATE INDEX "IX_SurveyOptions_QuestionId" ON "SurveyOptions" ("QuestionId");

CREATE INDEX "IX_SurveyOptions_QuestionId_DisplayOrder" ON "SurveyOptions" ("QuestionId", "DisplayOrder");

CREATE INDEX "IX_SurveyQuestions_SurveyId" ON "SurveyQuestions" ("SurveyId");

CREATE INDEX "IX_SurveyQuestions_SurveyId_DisplayOrder" ON "SurveyQuestions" ("SurveyId", "DisplayOrder");

CREATE INDEX "IX_SurveyResponses_EmployeeId" ON "SurveyResponses" ("EmployeeId");

CREATE UNIQUE INDEX "IX_SurveyResponses_SurveyId_EmployeeId" ON "SurveyResponses" ("SurveyId", "EmployeeId");

CREATE INDEX "IX_Surveys_IsMandatory" ON "Surveys" ("IsMandatory");

CREATE INDEX "IX_Surveys_Status" ON "Surveys" ("Status");

CREATE INDEX "IX_Surveys_SurveyType" ON "Surveys" ("SurveyType");

CREATE INDEX "IX_TaskAttachments_TaskId" ON "TaskAttachments" ("TaskId");

CREATE INDEX "IX_TaskAttachments_UploadedBy" ON "TaskAttachments" ("UploadedBy");

CREATE INDEX "IX_TaskComments_EmployeeId" ON "TaskComments" ("EmployeeId");

CREATE INDEX "IX_TaskComments_TaskId" ON "TaskComments" ("TaskId");

CREATE INDEX "IX_TaskHistories_ChangedBy" ON "TaskHistories" ("ChangedBy");

CREATE INDEX "IX_TaskHistories_TaskId" ON "TaskHistories" ("TaskId");

CREATE INDEX "IX_Tasks_AssignedBy" ON "Tasks" ("AssignedBy");

CREATE INDEX "IX_Tasks_AssignedTo" ON "Tasks" ("AssignedTo");

CREATE INDEX "IX_Tasks_DueDate" ON "Tasks" ("DueDate");

CREATE INDEX "IX_Tasks_Priority" ON "Tasks" ("Priority");

CREATE INDEX "IX_Tasks_RecurringTaskId" ON "Tasks" ("RecurringTaskId");

CREATE INDEX "IX_Tasks_Status" ON "Tasks" ("Status");

CREATE INDEX "IX_Tasks_TeamId" ON "Tasks" ("TeamId");

CREATE INDEX "IX_TaskTagMappings_TagId" ON "TaskTagMappings" ("TagId");

CREATE UNIQUE INDEX "IX_TaskTagMappings_TaskId_TagId" ON "TaskTagMappings" ("TaskId", "TagId");

CREATE UNIQUE INDEX "IX_TaskTags_Name" ON "TaskTags" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260726132016_AddCommunityEngagementModules', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Posts" ALTER COLUMN "Visibility" TYPE character varying(20);

ALTER TABLE "PostReactions" ALTER COLUMN "ReactionType" TYPE character varying(20);

ALTER TABLE "CommentReactions" ALTER COLUMN "ReactionType" TYPE character varying(20);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260729072837_SocialHubEnumConversion', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" ADD "CoverPhotoUrl" character varying(500);

UPDATE "Employees" SET "CoverPhotoUrl" = NULL
WHERE "EmployeeId" = 1;

UPDATE "Employees" SET "CoverPhotoUrl" = NULL
WHERE "EmployeeId" = 2;

UPDATE "Employees" SET "CoverPhotoUrl" = NULL
WHERE "EmployeeId" = 3;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260731134658_AddEmployeeCoverPhotoUrl', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Recognitions" ADD "BadgeId" bigint;

ALTER TABLE "Recognitions" ADD "IsHrIssued" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Badges" ADD "Color" character varying(20);

ALTER TABLE "Badges" ADD "IsActive" boolean NOT NULL DEFAULT TRUE;

CREATE INDEX "IX_Recognitions_BadgeId" ON "Recognitions" ("BadgeId");

ALTER TABLE "Recognitions" ADD CONSTRAINT "FK_Recognitions_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("BadgeId") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260731221725_AddRecognitionBadgeLinkAndHrAward', '10.0.5');

COMMIT;

START TRANSACTION;
UPDATE "PostReactions" SET "ReactionType" = 'Haha' WHERE "ReactionType" = 'Celebrate';
UPDATE "PostReactions" SET "ReactionType" = 'Like' WHERE "ReactionType" = 'Support';
UPDATE "PostReactions" SET "ReactionType" = 'Wow' WHERE "ReactionType" = 'Insightful';

UPDATE "CommentReactions" SET "ReactionType" = 'Haha' WHERE "ReactionType" = 'Celebrate';
UPDATE "CommentReactions" SET "ReactionType" = 'Like' WHERE "ReactionType" = 'Support';
UPDATE "CommentReactions" SET "ReactionType" = 'Wow' WHERE "ReactionType" = 'Insightful';

UPDATE "RecognitionReactions" SET "ReactionType" = 'Haha' WHERE "ReactionType" = 'Celebrate';
UPDATE "RecognitionReactions" SET "ReactionType" = 'Like' WHERE "ReactionType" = 'Support';
UPDATE "RecognitionReactions" SET "ReactionType" = 'Wow' WHERE "ReactionType" = 'Insightful';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260802153439_RemapReactionTypesToFacebookSet', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "EmployeeContactLinks" (
    "EmployeeContactLinkId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "Platform" character varying(50) NOT NULL,
    "Url" character varying(500) NOT NULL,
    "Visibility" character varying(20) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EmployeeContactLinks" PRIMARY KEY ("EmployeeContactLinkId"),
    CONSTRAINT "FK_EmployeeContactLinks_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId") ON DELETE CASCADE
);

CREATE INDEX "IX_EmployeeContactLinks_EmployeeId" ON "EmployeeContactLinks" ("EmployeeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804120310_AddEmployeeContactLinks', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" DROP COLUMN "GradeId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260804125319_RemoveEmployeeGradeId', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "RecognitionBadges" (
    "RecognitionBadgeId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RecognitionId" bigint NOT NULL,
    "BadgeId" bigint NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_RecognitionBadges" PRIMARY KEY ("RecognitionBadgeId"),
    CONSTRAINT "FK_RecognitionBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("BadgeId") ON DELETE CASCADE,
    CONSTRAINT "FK_RecognitionBadges_Recognitions_RecognitionId" FOREIGN KEY ("RecognitionId") REFERENCES "Recognitions" ("RecognitionId") ON DELETE CASCADE
);

CREATE INDEX "IX_RecognitionBadges_BadgeId" ON "RecognitionBadges" ("BadgeId");

CREATE UNIQUE INDEX "IX_RecognitionBadges_RecognitionId_BadgeId" ON "RecognitionBadges" ("RecognitionId", "BadgeId");


                INSERT INTO "RecognitionBadges" ("RecognitionId", "BadgeId", "TenantId", "Status", "CreatedAt")
                SELECT "RecognitionId", "BadgeId", "TenantId", 0, COALESCE("CreatedAt", now())
                FROM "Recognitions"
                WHERE "BadgeId" IS NOT NULL;
            

ALTER TABLE "Recognitions" DROP CONSTRAINT "FK_Recognitions_Badges_BadgeId";

DROP INDEX "IX_Recognitions_BadgeId";

ALTER TABLE "Recognitions" DROP COLUMN "BadgeId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260806191324_AddRecognitionBadgesJoinTable', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Posts" ADD "GroupId" bigint;

CREATE TABLE "Groups" (
    "GroupId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "Visibility" character varying(20) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("GroupId")
);

CREATE TABLE "GroupJoinRequests" (
    "GroupJoinRequestId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "Status" character varying(20) NOT NULL,
    "ResolvedByEmployeeId" bigint,
    "ResolvedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_GroupJoinRequests" PRIMARY KEY ("GroupJoinRequestId"),
    CONSTRAINT "FK_GroupJoinRequests_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("GroupId") ON DELETE CASCADE
);

CREATE TABLE "GroupMembers" (
    "GroupMemberId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "Role" character varying(20) NOT NULL,
    "JoinedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("GroupMemberId"),
    CONSTRAINT "FK_GroupMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("GroupId") ON DELETE CASCADE
);

CREATE INDEX "IX_Posts_GroupId" ON "Posts" ("GroupId");

CREATE INDEX "IX_GroupJoinRequests_EmployeeId" ON "GroupJoinRequests" ("EmployeeId");

CREATE INDEX "IX_GroupJoinRequests_GroupId_EmployeeId_Status" ON "GroupJoinRequests" ("GroupId", "EmployeeId", "Status");

CREATE INDEX "IX_GroupMembers_EmployeeId" ON "GroupMembers" ("EmployeeId");

CREATE UNIQUE INDEX "IX_GroupMembers_GroupId_EmployeeId" ON "GroupMembers" ("GroupId", "EmployeeId");

CREATE INDEX "IX_GroupMembers_Role" ON "GroupMembers" ("Role");

CREATE INDEX "IX_Groups_Name" ON "Groups" ("Name");

CREATE INDEX "IX_Groups_Visibility" ON "Groups" ("Visibility");

ALTER TABLE "Posts" ADD CONSTRAINT "FK_Posts_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Groups" ("GroupId") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260806221411_AddGroupsModule', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "Branches" (
    "BranchId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Address" text,
    "City" character varying(100),
    "Country" character varying(100),
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Branches" PRIMARY KEY ("BranchId")
);

CREATE TABLE "Departments" (
    "DepartmentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Code" character varying(50),
    "Description" text,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("DepartmentId")
);

CREATE TABLE "Designations" (
    "DesignationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Grade" character varying(50),
    "Description" text,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Designations" PRIMARY KEY ("DesignationId")
);

CREATE TABLE "Roles" (
    "RoleId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE INDEX "IX_Branches_IsActive" ON "Branches" ("IsActive");

CREATE INDEX "IX_Departments_IsActive" ON "Departments" ("IsActive");

CREATE INDEX "IX_Designations_IsActive" ON "Designations" ("IsActive");

CREATE INDEX "IX_Roles_IsActive" ON "Roles" ("IsActive");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260808194540_AddDepartmentBranchDesignationRole', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Surveys" ADD "ExternalUrl" character varying(2048);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260809101351_AddSurveyExternalUrl', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Listings" ADD "Quantity" integer NOT NULL DEFAULT 1;

CREATE TABLE "Purchases" (
    "PurchaseId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" bigint NOT NULL,
    "BuyerId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Purchases" PRIMARY KEY ("PurchaseId"),
    CONSTRAINT "FK_Purchases_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE RESTRICT
);

CREATE TABLE "Reviews" (
    "ReviewId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" bigint NOT NULL,
    "ReviewerId" bigint NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("ListingId") ON DELETE CASCADE
);

CREATE TABLE "ReviewImages" (
    "ImageId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReviewId" bigint NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ReviewImages" PRIMARY KEY ("ImageId"),
    CONSTRAINT "FK_ReviewImages_Reviews_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews" ("ReviewId") ON DELETE CASCADE
);

CREATE INDEX "IX_Purchases_BuyerId" ON "Purchases" ("BuyerId");

CREATE INDEX "IX_Purchases_ListingId" ON "Purchases" ("ListingId");

CREATE INDEX "IX_ReviewImages_ReviewId" ON "ReviewImages" ("ReviewId");

CREATE INDEX "IX_Reviews_ListingId" ON "Reviews" ("ListingId");

CREATE UNIQUE INDEX "IX_Reviews_ListingId_ReviewerId" ON "Reviews" ("ListingId", "ReviewerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260814214016_AddMarketplaceStockPurchaseReview', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "SurveyAnswers" ADD "RatingValue" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260818091142_AddSurveyAnswerRatingValue', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Tasks" DROP CONSTRAINT "FK_Tasks_Teams_TeamId";

ALTER TABLE "Tasks" ALTER COLUMN "TeamId" DROP NOT NULL;

ALTER TABLE "Tasks" ADD CONSTRAINT "FK_Tasks_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Teams" ("TeamId") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260818115719_MakeTaskTeamIdNullable', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "EmployeeKeycloakAccounts" (
    "EmployeeKeycloakAccountId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" bigint NOT NULL,
    "KeycloakUserId" character varying(64) NOT NULL,
    "Username" character varying(200) NOT NULL,
    "AssignedRole" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_EmployeeKeycloakAccounts" PRIMARY KEY ("EmployeeKeycloakAccountId")
);

CREATE UNIQUE INDEX "IX_EmployeeKeycloakAccounts_EmployeeId" ON "EmployeeKeycloakAccounts" ("EmployeeId");

CREATE UNIQUE INDEX "IX_EmployeeKeycloakAccounts_Username" ON "EmployeeKeycloakAccounts" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820150236_AddEmployeeKeycloakAccount', '10.0.5');

COMMIT;

START TRANSACTION;
DROP TABLE "TaskTagMappings";

DROP TABLE "TaskTags";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820220530_RemoveTaskTags', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" ADD "DateOfBirth" date;

ALTER TABLE "Employees" ADD "DateOfJoining" date;

INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (2, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Human Resources', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (3, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Sales & Marketing', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (4, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Finance', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (5, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Operations', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (6, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Customer Support', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (7, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'Legal', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Departments" ("DepartmentId", "Code", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (8, NULL, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, TRUE, 'IT Infrastructure', NULL, 0, 'default_tenant', NULL, NULL);

INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (2, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Senior Software Engineer', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (3, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'HR Manager', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (4, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Sales Executive', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (5, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Financial Analyst', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (6, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Operations Lead', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (7, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Support Specialist', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (8, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Legal Counsel', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (9, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'System Administrator', NULL, 0, 'default_tenant', NULL, NULL);
INSERT INTO "Designations" ("DesignationId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "Description", "Grade", "IsActive", "Name", "Remarks", "Status", "TenantId", "UpdatedAt", "UpdatedBy")
VALUES (10, TIMESTAMPTZ '2025-01-01T00:00:00Z', NULL, NULL, NULL, NULL, NULL, TRUE, 'Team Lead', NULL, 0, 'default_tenant', NULL, NULL);

UPDATE "Employees" SET "DateOfBirth" = NULL, "DateOfJoining" = NULL
WHERE "EmployeeId" = 1;

UPDATE "Employees" SET "DateOfBirth" = NULL, "DateOfJoining" = NULL
WHERE "EmployeeId" = 2;

UPDATE "Employees" SET "DateOfBirth" = NULL, "DateOfJoining" = NULL
WHERE "EmployeeId" = 3;

SELECT setval(
    pg_get_serial_sequence('"Departments"', 'DepartmentId'),
    GREATEST(
        (SELECT MAX("DepartmentId") FROM "Departments") + 1,
        nextval(pg_get_serial_sequence('"Departments"', 'DepartmentId'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Designations"', 'DesignationId'),
    GREATEST(
        (SELECT MAX("DesignationId") FROM "Designations") + 1,
        nextval(pg_get_serial_sequence('"Designations"', 'DesignationId'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260824232250_AddEmployeeBirthAndJoiningDates', '10.0.5');

COMMIT;

START TRANSACTION;
CREATE TABLE "ChatConversations" (
    "ChatConversationId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(20) NOT NULL,
    "Title" character varying(200),
    "GroupAvatarFileId" bigint,
    "CreatedByEmployeeId" bigint NOT NULL,
    "LastMessageAt" timestamp with time zone,
    "LastMessagePreview" character varying(200),
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ChatConversations" PRIMARY KEY ("ChatConversationId")
);

CREATE TABLE "ChatMessages" (
    "ChatMessageId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChatConversationId" bigint NOT NULL,
    "SenderEmployeeId" bigint NOT NULL,
    "Body" text,
    "MessageType" character varying(20) NOT NULL,
    "SharedContentType" character varying(20),
    "SharedContentId" bigint,
    "SentAt" timestamp with time zone NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("ChatMessageId"),
    CONSTRAINT "FK_ChatMessages_ChatConversations_ChatConversationId" FOREIGN KEY ("ChatConversationId") REFERENCES "ChatConversations" ("ChatConversationId") ON DELETE RESTRICT
);

CREATE TABLE "ChatParticipants" (
    "ChatParticipantId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChatConversationId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "LeftAt" timestamp with time zone,
    "LastReadAt" timestamp with time zone,
    "IsMuted" boolean NOT NULL,
    "IsPinned" boolean NOT NULL,
    "PinnedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ChatParticipants" PRIMARY KEY ("ChatParticipantId"),
    CONSTRAINT "FK_ChatParticipants_ChatConversations_ChatConversationId" FOREIGN KEY ("ChatConversationId") REFERENCES "ChatConversations" ("ChatConversationId") ON DELETE RESTRICT
);

CREATE TABLE "ChatMessageAttachments" (
    "ChatMessageAttachmentId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChatMessageId" bigint NOT NULL,
    "FileStorageId" bigint NOT NULL,
    "AttachmentType" character varying(20) NOT NULL,
    "DurationSeconds" integer,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ChatMessageAttachments" PRIMARY KEY ("ChatMessageAttachmentId"),
    CONSTRAINT "FK_ChatMessageAttachments_ChatMessages_ChatMessageId" FOREIGN KEY ("ChatMessageId") REFERENCES "ChatMessages" ("ChatMessageId") ON DELETE RESTRICT,
    CONSTRAINT "FK_ChatMessageAttachments_FileStorages_FileStorageId" FOREIGN KEY ("FileStorageId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT
);

CREATE TABLE "ChatMessageReactions" (
    "ChatMessageReactionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ChatMessageId" bigint NOT NULL,
    "EmployeeId" bigint NOT NULL,
    "ReactionType" character varying(20) NOT NULL,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_ChatMessageReactions" PRIMARY KEY ("ChatMessageReactionId"),
    CONSTRAINT "FK_ChatMessageReactions_ChatMessages_ChatMessageId" FOREIGN KEY ("ChatMessageId") REFERENCES "ChatMessages" ("ChatMessageId") ON DELETE RESTRICT
);

CREATE TABLE "ChatReports" (
    "ChatReportId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReportedByEmployeeId" bigint NOT NULL,
    "ChatConversationId" bigint NOT NULL,
    "ChatMessageId" bigint,
    "Reason" text NOT NULL,
    "Status" character varying(50) NOT NULL,
    "ReviewedBy" bigint,
    "ReviewedAt" timestamp with time zone,
    "TenantId" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone,
    "CreatedBy" bigint,
    "UpdatedAt" timestamp with time zone,
    "UpdatedBy" bigint,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" bigint,
    CONSTRAINT "PK_ChatReports" PRIMARY KEY ("ChatReportId"),
    CONSTRAINT "FK_ChatReports_ChatConversations_ChatConversationId" FOREIGN KEY ("ChatConversationId") REFERENCES "ChatConversations" ("ChatConversationId") ON DELETE RESTRICT,
    CONSTRAINT "FK_ChatReports_ChatMessages_ChatMessageId" FOREIGN KEY ("ChatMessageId") REFERENCES "ChatMessages" ("ChatMessageId") ON DELETE RESTRICT
);

CREATE INDEX "IX_ChatConversations_CreatedByEmployeeId" ON "ChatConversations" ("CreatedByEmployeeId");

CREATE INDEX "IX_ChatConversations_LastMessageAt" ON "ChatConversations" ("LastMessageAt");

CREATE INDEX "IX_ChatMessageAttachments_ChatMessageId" ON "ChatMessageAttachments" ("ChatMessageId");

CREATE INDEX "IX_ChatMessageAttachments_FileStorageId" ON "ChatMessageAttachments" ("FileStorageId");

CREATE UNIQUE INDEX "IX_ChatMessageReactions_ChatMessageId_EmployeeId" ON "ChatMessageReactions" ("ChatMessageId", "EmployeeId");

CREATE INDEX "IX_ChatMessages_ChatConversationId_SentAt" ON "ChatMessages" ("ChatConversationId", "SentAt");

CREATE INDEX "IX_ChatMessages_SenderEmployeeId" ON "ChatMessages" ("SenderEmployeeId");

CREATE INDEX "IX_ChatParticipants_ChatConversationId_EmployeeId" ON "ChatParticipants" ("ChatConversationId", "EmployeeId");

CREATE INDEX "IX_ChatParticipants_EmployeeId" ON "ChatParticipants" ("EmployeeId");

CREATE INDEX "IX_ChatReports_ChatConversationId" ON "ChatReports" ("ChatConversationId");

CREATE INDEX "IX_ChatReports_ChatMessageId" ON "ChatReports" ("ChatMessageId");

CREATE INDEX "IX_ChatReports_ReportedByEmployeeId" ON "ChatReports" ("ReportedByEmployeeId");

CREATE INDEX "IX_ChatReports_Status" ON "ChatReports" ("Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260828111821_AddMessengerModule', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ChatMessages" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "ChatMessages" ADD "IsForwarded" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "ChatMessages" ADD "ReplyToMessageId" bigint;

CREATE INDEX "IX_ChatMessages_ReplyToMessageId" ON "ChatMessages" ("ReplyToMessageId");

ALTER TABLE "ChatMessages" ADD CONSTRAINT "FK_ChatMessages_ChatMessages_ReplyToMessageId" FOREIGN KEY ("ReplyToMessageId") REFERENCES "ChatMessages" ("ChatMessageId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260828211057_AddMessageActions', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" DROP COLUMN "RFId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260830094616_RemoveEmployeeRFId', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ChatConversations" ADD "OnlyAdminsCanAddMembers" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260903115943_AddGroupAddMemberPermission', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ChatMessages" ADD "IsPinned" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "ChatMessages" ADD "PinnedAt" timestamp with time zone;

ALTER TABLE "ChatMessages" ADD "PinnedByEmployeeId" bigint;

CREATE INDEX "IX_ChatMessages_ChatConversationId_IsPinned" ON "ChatMessages" ("ChatConversationId", "IsPinned");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260904131624_AddChatMessagePinFields', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ElectionCandidates" DROP COLUMN "IsApproved";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260904201300_RemoveElectionCandidateIsApproved', '10.0.5');

COMMIT;

START TRANSACTION;
DROP TABLE "ReviewImages";

DROP TABLE "Reviews";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260905152857_RemoveMarketplaceReviews', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskAttachments" ADD "FileStorageId" bigint;

ALTER TABLE "PostAttachments" ADD "FileStorageId" bigint;

ALTER TABLE "ListingImages" ADD "FileStorageId" bigint;

CREATE INDEX "IX_TaskAttachments_FileStorageId" ON "TaskAttachments" ("FileStorageId");

CREATE INDEX "IX_PostAttachments_FileStorageId" ON "PostAttachments" ("FileStorageId");

CREATE INDEX "IX_ListingImages_FileStorageId" ON "ListingImages" ("FileStorageId");

ALTER TABLE "ListingImages" ADD CONSTRAINT "FK_ListingImages_FileStorages_FileStorageId" FOREIGN KEY ("FileStorageId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

ALTER TABLE "PostAttachments" ADD CONSTRAINT "FK_PostAttachments_FileStorages_FileStorageId" FOREIGN KEY ("FileStorageId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

ALTER TABLE "TaskAttachments" ADD CONSTRAINT "FK_TaskAttachments_FileStorages_FileStorageId" FOREIGN KEY ("FileStorageId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260906051001_AddFileStorageIdToAttachments', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Employees" ADD "CoverPhotoFileId" bigint;

ALTER TABLE "Employees" ADD "PhotoFileId" bigint;

UPDATE "Employees" SET "CoverPhotoFileId" = NULL, "PhotoFileId" = NULL
WHERE "EmployeeId" = 1;

UPDATE "Employees" SET "CoverPhotoFileId" = NULL, "PhotoFileId" = NULL
WHERE "EmployeeId" = 2;

UPDATE "Employees" SET "CoverPhotoFileId" = NULL, "PhotoFileId" = NULL
WHERE "EmployeeId" = 3;

CREATE INDEX "IX_Employees_CoverPhotoFileId" ON "Employees" ("CoverPhotoFileId");

CREATE INDEX "IX_Employees_PhotoFileId" ON "Employees" ("PhotoFileId");

CREATE INDEX "IX_ChatConversations_GroupAvatarFileId" ON "ChatConversations" ("GroupAvatarFileId");

ALTER TABLE "ChatConversations" ADD CONSTRAINT "FK_ChatConversations_FileStorages_GroupAvatarFileId" FOREIGN KEY ("GroupAvatarFileId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_FileStorages_CoverPhotoFileId" FOREIGN KEY ("CoverPhotoFileId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

ALTER TABLE "Employees" ADD CONSTRAINT "FK_Employees_FileStorages_PhotoFileId" FOREIGN KEY ("PhotoFileId") REFERENCES "FileStorages" ("FileId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260906101420_AddEmployeePhotoFileIdsAndGroupAvatarFk', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "ChatMessageAttachments" ADD "FilePath" character varying(1000) NOT NULL DEFAULT '';

UPDATE "ChatMessageAttachments" AS cma
SET "FilePath" = fs."StoragePath"
FROM "FileStorages" AS fs
WHERE fs."FileId" = cma."FileStorageId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260906104529_AddFilePathToChatMessageAttachments', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Elections" ADD "PublishedAt" timestamp with time zone;

UPDATE "Elections" SET "PublishedAt" = COALESCE("UpdatedAt", "CreatedAt") WHERE "Status" <> 'Draft';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260920183429_AddElectionPublishedAt', '10.0.5');

COMMIT;

