namespace SylviaNG.Community.Application.Features.Employees.Models
{
    /// <summary>
    /// HR/Admin "Add Employee" request (US-1.6). EmployeeCode is generated by the service.
    /// </summary>
    public class EmployeeCreateRequest
    {
        public string EmployeeName { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public long DesignationId { get; set; }
        public long DepartmentId { get; set; }
        public long SiteId { get; set; }
    }
}
